#!/bin/bash
# Copyright 2014 Alfonso Garcia-Patiño Barbolani (barbolani@gmail.com)
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#
# Automates OpenSuse 13.2 installation of Oracle Java 8 SDK.
#
# Mostly follows instructions at http://en.opensuse.org/SDB:Installing_Java,
# automating them so that next time you install an Oracle JDK you won't have
# to copy and paste such long commands.
#
#
# How to use:
#   1- Download the desired Java rpm JDK from http://www.oracle.com (32 or 64
#      bit according to your platform), and optionally, the API documentation.
#   2- Install the JDK by command line: zypper install <rpm file>
#      or by double clicking on the rpm file.
#   3- Install API documentation. Optional, but javadocdir update will fail.
#   4- Adjust the variables below to reflect:
#      - The Java version and revision being installed.
#      - The location of the install. In OpenSuse this is either
#        /usr/lib (32 bit) or /usr/lib64 (64 bits).
#      - The target architecture i386 (32 bit) or amd64 (64 bit).
#   5- Run this script as root from a command line
#   6- Afterwards, select the desired Oracle Java implementation with:
#     Runtime:         update-alternatives --config java
#     Compiler:        update-alternatives --config javac
#     Browser plugin:  update-alternatives --config javaplugin
#     App launcher:    update-alternatives --config jre_<java version>
#     Exported JARs:   update-alternatives --config java_sdk_<java version>
#     [If installed...]
#     Documentation:   update-alternatives --config javadocdir
#
#
# Set these variables according to the Java version to be installed:
JAVA_VERSION=1.8.0               # JAVA_VERSION  = 1.8.0
JAVA_REVISION=${JAVA_VERSION}_60 # JAVA_REVISION = 1.8.0_60
ARCHITECTURE=amd64               # ARCHITECTURE  = i386 or amd64
PRIORITY=18060                   # PRIORITY      = <your priority>
LIB_FOLDER=/usr/lib64            # LIB_FOLDER    = /usr/lib(64)
                                 # JVM_FOLDER    = /usr/lib(64)/jvm/jdk1.8.0_60
JVM_FOLDER=${LIB_FOLDER}/jvm/jdk${JAVA_REVISION}


# Compress the java man pages.
for f in ${JVM_FOLDER}/man/man1/*.1 ; do gzip $(readlink -f $f) ; done ;


# Setup the jvm-exports.
mkdir -p ${LIB_FOLDER}/jvm-exports/jdk${JAVA_REVISION}
cd ${LIB_FOLDER}/jvm-exports/jdk${JAVA_REVISION}
ln -s ${JVM_FOLDER}/jre/lib/rt.jar jaas-${JAVA_REVISION}.jar
ln -s jaas-${JAVA_REVISION}.jar jaas-${JAVA_VERSION}.jar
ln -s jaas-${JAVA_REVISION}.jar jaas.jar
ln -s ${JVM_FOLDER}/jre/lib/jce.jar jce-${JAVA_REVISION}.jar
ln -s jce-${JAVA_REVISION}.jar jce-${JAVA_VERSION}.jar
ln -s jce-${JAVA_REVISION}.jar jce.jar
ln -s ${JVM_FOLDER}/jre/lib/rt.jar jdbc-stdext-${JAVA_REVISION}.jar
ln -s jdbc-stdext-${JAVA_REVISION}.jar jdbc-stdext-${JAVA_VERSION}.jar
ln -s jdbc-stdext-${JAVA_REVISION}.jar jdbc-stdext-3.0.jar
ln -s jdbc-stdext-${JAVA_REVISION}.jar jdbc-stdext.jar
ln -s ${JVM_FOLDER}/jre/lib/rt.jar jndi-${JAVA_REVISION}.jar
ln -s jndi-${JAVA_REVISION}.jar jndi-${JAVA_VERSION}.jar
ln -s jndi-${JAVA_REVISION}.jar jndi.jar
ln -s ${JVM_FOLDER}/jre/lib/rt.jar jndi-cos-${JAVA_REVISION}.jar
ln -s jndi-cos-${JAVA_REVISION}.jar jndi-cos-${JAVA_VERSION}.jar
ln -s jndi-cos-${JAVA_REVISION}.jar jndi-cos.jar
ln -s ${JVM_FOLDER}/jre/lib/rt.jar jndi-ldap-${JAVA_REVISION}.jar
ln -s jndi-ldap-${JAVA_REVISION}.jar jndi-ldap-${JAVA_VERSION}.jar
ln -s jndi-ldap-${JAVA_REVISION}.jar jndi-ldap.jar
ln -s ${JVM_FOLDER}/jre/lib/rt.jar jndi-rmi-${JAVA_REVISION}.jar
ln -s jndi-rmi-${JAVA_REVISION}.jar jndi-rmi-${JAVA_VERSION}.jar
ln -s jndi-rmi-${JAVA_REVISION}.jar jndi-rmi.jar
ln -s ${JVM_FOLDER}/jre/lib/jsse.jar jsse-${JAVA_REVISION}.jar
ln -s jsse-${JAVA_REVISION}.jar jsse-${JAVA_VERSION}.jar
ln -s jsse-${JAVA_REVISION}.jar jsse.jar
ln -s ${JVM_FOLDER}/jre/lib/rt.jar sasl-${JAVA_REVISION}.jar
ln -s sasl-${JAVA_REVISION}.jar sasl-${JAVA_VERSION}.jar
ln -s sasl-${JAVA_REVISION}.jar sasl.jar


# >>> java <<< Symbolic links to java JRE commands.
/usr/sbin/update-alternatives --install /usr/bin/java java ${JVM_FOLDER}/bin/java ${PRIORITY} \
  --slave ${LIB_FOLDER}/jvm/jre jre ${JVM_FOLDER}/jre \
  --slave ${LIB_FOLDER}/jvm-exports/jre jre_exports ${LIB_FOLDER}/jvm-exports/jdk${JAVA_REVISION} \
  --slave /usr/share/man/man1/java.1.gz java.1.gz ${JVM_FOLDER}/man/man1/java.1.gz \
  --slave /usr/bin/keytool keytool ${JVM_FOLDER}/bin/keytool \
  --slave /usr/share/man/man1/keytool.1.gz keytool.1.gz ${JVM_FOLDER}/man/man1/keytool.1.gz \
  --slave /usr/bin/orbd orbd ${JVM_FOLDER}/bin/orbd \
  --slave /usr/share/man/man1/orbd.1.gz orbd.1.gz ${JVM_FOLDER}/man/man1/orbd.1.gz \
  --slave /usr/bin/policytool policytool ${JVM_FOLDER}/bin/policytool \
  --slave /usr/share/man/man1/policytool.1.gz policytool.1.gz ${JVM_FOLDER}/man/man1/policytool.1.gz \
  --slave /usr/bin/rmid rmid ${JVM_FOLDER}/bin/rmid \
  --slave /usr/share/man/man1/rmid.1.gz rmid.1.gz ${JVM_FOLDER}/man/man1/rmid.1.gz \
  --slave /usr/bin/rmiregistry rmiregistry ${JVM_FOLDER}/bin/rmiregistry \
  --slave /usr/share/man/man1/rmiregistry.1.gz rmiregistry.1.gz ${JVM_FOLDER}/man/man1/rmiregistry.1.gz \
  --slave /usr/bin/servertool servertool ${JVM_FOLDER}/bin/servertool \
  --slave /usr/share/man/man1/servertool.1.gz servertool.1.gz ${JVM_FOLDER}/man/man1/servertool.1.gz \
  --slave /usr/bin/tnameserv tnameserv ${JVM_FOLDER}/bin/tnameserv \
  --slave /usr/share/man/man1/tnameserv.1.gz tnameserv.1.gz ${JVM_FOLDER}/man/man1/tnameserv.1.gz


# >>> javac <<< Symbolic links to java JDK commands.
/usr/sbin/update-alternatives --install /usr/bin/javac javac ${JVM_FOLDER}/bin/javac ${PRIORITY} \
  --slave ${LIB_FOLDER}/jvm/java java_sdk ${JVM_FOLDER} \
  --slave ${LIB_FOLDER}/jvm-exports/java java_sdk_exports ${LIB_FOLDER}/jvm-exports/jdk${JAVA_REVISION} \
  --slave /usr/share/man/man1/javac.1.gz javac.1.gz ${JVM_FOLDER}/man/man1/javac.1.gz \
  --slave /usr/bin/appletviewer appletviewer ${JVM_FOLDER}/bin/appletviewer \
  --slave /usr/share/man/man1/appletviewer.1.gz appletviewer.1.gz ${JVM_FOLDER}/man/man1/appletviewer.1.gz \
  # Part of Java 7, removed from 8.
  #--slave /usr/bin/apt apt ${LIB_FOLDER}/jdk_Oracle/bin/apt \
  #--slave /usr/share/man/man1/apt.1.gz apt.1.gz ${LIB_FOLDER}/jdk_Oracle/man/man1/apt.1.gz \
  --slave /usr/bin/extcheck extcheck ${JVM_FOLDER}/bin/extcheck \
  --slave /usr/share/man/man1/extcheck.1.gz extcheck.1.gz ${JVM_FOLDER}/man/man1/extcheck.1.gz \
  --slave /usr/bin/jar jar ${JVM_FOLDER}/bin/jar \
  --slave /usr/share/man/man1/jar.1.gz jar.1.gz ${JVM_FOLDER}/man/man1/jar.1.gz \
  --slave /usr/bin/jarsigner jarsigner ${JVM_FOLDER}/bin/jarsigner \
  --slave /usr/share/man/man1/jarsigner.1.gz jarsigner.1.gz ${JVM_FOLDER}/man/man1/jarsigner.1.gz \
  --slave /usr/bin/javadoc javadoc ${JVM_FOLDER}/bin/javadoc \
  --slave /usr/share/man/man1/javadoc.1.gz javadoc.1.gz ${JVM_FOLDER}/man/man1/javadoc.1.gz \
  --slave /usr/bin/javah javah ${JVM_FOLDER}/bin/javah \
  --slave /usr/share/man/man1/javah.1.gz javah.1.gz ${JVM_FOLDER}/man/man1/javah.1.gz \
  --slave /usr/bin/javap javap ${JVM_FOLDER}/bin/javap \
  --slave /usr/share/man/man1/javap.1.gz javap.1.gz ${JVM_FOLDER}/man/man1/javap.1.gz \
  --slave /usr/bin/jcmd jcmd ${JVM_FOLDER}/bin/jcmd \
  --slave /usr/share/man/man1/jcmd.1.gz jcmd.1.gz ${JVM_FOLDER}/man/man1/jcmd.1.gz \
  --slave /usr/bin/jconsole jconsole ${JVM_FOLDER}/bin/jconsole \
  --slave /usr/share/man/man1/jconsole.1.gz jconsole.1.gz ${JVM_FOLDER}/man/man1/jconsole.1.gz \
  --slave /usr/bin/jdb jdb ${JVM_FOLDER}/bin/jdb \
  --slave /usr/share/man/man1/jdb.1.gz jdb.1.gz ${JVM_FOLDER}/man/man1/jdb.1.gz \
  --slave /usr/bin/jhat jhat ${JVM_FOLDER}/bin/jhat \
  --slave /usr/share/man/man1/jhat.1.gz jhat.1.gz ${JVM_FOLDER}/man/man1/jhat.1.gz \
  --slave /usr/bin/jinfo jinfo ${JVM_FOLDER}/bin/jinfo \
  --slave /usr/share/man/man1/jinfo.1.gz jinfo.1.gz ${JVM_FOLDER}/man/man1/jinfo.1.gz \
  --slave /usr/bin/jmap jmap ${JVM_FOLDER}/bin/jmap \
  --slave /usr/share/man/man1/jmap.1.gz jmap.1.gz ${JVM_FOLDER}/man/man1/jmap.1.gz \
  --slave /usr/bin/jps jps ${JVM_FOLDER}/bin/jps \
  --slave /usr/share/man/man1/jps.1.gz jps.1.gz ${JVM_FOLDER}/man/man1/jps.1.gz \
  --slave /usr/bin/jrunscript jrunscript ${JVM_FOLDER}/bin/jrunscript \
  --slave /usr/share/man/man1/jrunscript.1.gz jrunscript.1.gz ${JVM_FOLDER}/man/man1/jrunscript.1.gz \
  --slave /usr/bin/jsadebugd jsadebugd ${JVM_FOLDER}/bin/jsadebugd \
  --slave /usr/share/man/man1/jsadebugd.1.gz jsadebugd.1.gz ${JVM_FOLDER}/man/man1/jsadebugd.1.gz \
  --slave /usr/bin/jstack jstack ${JVM_FOLDER}/bin/jstack \
  --slave /usr/share/man/man1/jstack.1.gz jstack.1.gz ${JVM_FOLDER}/man/man1/jstack.1.gz \
  --slave /usr/bin/jstat jstat ${JVM_FOLDER}/bin/jstat \
  --slave /usr/share/man/man1/jstat.1.gz jstat.1.gz ${JVM_FOLDER}/man/man1/jstat.1.gz \
  --slave /usr/bin/jstatd jstatd ${JVM_FOLDER}/bin/jstatd \
  --slave /usr/share/man/man1/jstatd.1.gz jstatd.1.gz ${JVM_FOLDER}/man/man1/jstatd.1.gz \
  --slave /usr/bin/native2ascii native2ascii ${JVM_FOLDER}/bin/native2ascii \
  --slave /usr/share/man/man1/native2ascii.1.gz native2ascii.1.gz ${JVM_FOLDER}/man/man1/native2ascii.1.gz \
  --slave /usr/bin/pack200 pack200 ${JVM_FOLDER}/bin/pack200 \
  --slave /usr/share/man/man1/pack200.1.gz pack200.1.gz ${JVM_FOLDER}/man/man1/pack200.1.gz \
  --slave /usr/bin/rmic rmic ${JVM_FOLDER}/bin/rmic \
  --slave /usr/share/man/man1/rmic.1.gz rmic.1.gz ${JVM_FOLDER}/man/man1/rmic.1.gz \
  --slave /usr/bin/schemagen schemagen ${JVM_FOLDER}/bin/schemagen \
  --slave /usr/share/man/man1/schemagen.1.gz schemagen.1.gz ${JVM_FOLDER}/man/man1/schemagen.1.gz \
  --slave /usr/bin/serialver serialver ${JVM_FOLDER}/bin/serialver \
  --slave /usr/share/man/man1/serialver.1.gz serialver.1.gz ${JVM_FOLDER}/man/man1/serialver.1.gz \
  --slave /usr/bin/unpack200 unpack200 ${JVM_FOLDER}/bin/unpack200 \
  --slave /usr/share/man/man1/unpack200.1.gz unpack200.1.gz ${JVM_FOLDER}/man/man1/unpack200.1.gz \
  --slave /usr/bin/wsgen wsgen ${JVM_FOLDER}/bin/wsgen \
  --slave /usr/share/man/man1/wsgen.1.gz wsgen.1.gz ${JVM_FOLDER}/man/man1/wsgen.1.gz \
  --slave /usr/bin/wsimport wsimport ${JVM_FOLDER}/bin/wsimport \
  --slave /usr/share/man/man1/wsimport.1.gz wsimport.1.gz ${JVM_FOLDER}/man/man1/wsimport.1.gz \
  --slave /usr/bin/xjc xjc ${JVM_FOLDER}/bin/xjc \
  --slave /usr/share/man/man1/xjc.1.gz xjc.1.gz ${JVM_FOLDER}/man/man1/xjc.1.gz


# >>> javaplugin <<< Symbolic links to Web browser plugin commands.
/usr/sbin/update-alternatives --install ${LIB_FOLDER}/browser-plugins/javaplugin.so javaplugin ${JVM_FOLDER}/jre/lib/${ARCHITECTURE}/libnpjp2.so ${PRIORITY} \
  --slave /usr/bin/javaws javaws ${JVM_FOLDER}/jre/bin/javaws \
  --slave /usr/share/man/man1/javaws.1 javaws.1 ${JVM_FOLDER}/man/man1/javaws.1.gz


# >>> java_jre_1.8.0 <<< Symbolic links to java 1.8.0 JRE commands.
/usr/sbin/update-alternatives --install ${LIB_FOLDER}/jvm/jre-${JAVA_VERSION} jre_${JAVA_VERSION} ${JVM_FOLDER}/jre ${PRIORITY} \
  --slave ${LIB_FOLDER}/jvm-exports/jre-${JAVA_VERSION} jre_${JAVA_VERSION}_exports ${LIB_FOLDER}/jvm-exports/jdk${JAVA_REVISION}


# >>> java_sdk_1.8.0 <<< Symbolic links to java 1.8.0 JDK commands.
/usr/sbin/update-alternatives --install ${LIB_FOLDER}/jvm/java-${JAVA_VERSION} java_sdk_${JAVA_VERSION} ${JVM_FOLDER} ${PRIORITY} \
  --slave ${LIB_FOLDER}/jvm-exports/java-${JAVA_VERSION} java_sdk_${JAVA_VERSION}_exports ${LIB_FOLDER}/jvm-exports/jdk${JAVA_REVISION}


# >>> javadocdir <<< Symbolic links to java API documentation.
/usr/sbin/update-alternatives --install /usr/share/javadoc/java javadocdir /usr/share/javadoc/jdk${JAVA_REVISION}/api ${PRIORITY}


# Expose Sun's Java control panel and various icons.
ln -s ${JVM_FOLDER}/jre/bin/jcontrol /usr/bin/
ln -s ${JVM_FOLDER}/jre/lib/desktop/icons/hicolor/16x16/apps/sun-jcontrol.png /usr/share/icons/hicolor/16x16/apps/
ln -s ${JVM_FOLDER}/jre/lib/desktop/icons/hicolor/48x48/apps/sun-jcontrol.png /usr/share/icons/hicolor/48x48/apps/
ln -s ${JVM_FOLDER}/jre/lib/desktop/icons/LowContrast/16x16/apps/sun-jcontrol.png /usr/share/icons/locolor/16x16/apps/
ln -s ${JVM_FOLDER}/jre/lib/desktop/icons/LowContrast/48x48/apps/sun-jcontrol.png /usr/share/icons/locolor/48x48/apps/
ln -s ${JVM_FOLDER}/jre/lib/desktop/applications/sun_java.desktop /usr/share/applications
